#!/bin/bash
#AUTHOR: Younghun Ju <younghoon.ju@rnd.yujinrobot.com>, <yhju83@gmail.com>

# 1. Laptop Battery
# check for existence of /proc/acpi/battery/BAT? directories
BAT_PREFIX=/proc/acpi/battery
FOUND=-1
for idx in `seq 10`; do 
  if [ -e $BAT_PREFIX/BAT$((idx-1)) ]; then
    BAT="BAT"$((idx-1))
    FOUND=0
    break
  fi
done

if [ $FOUND -eq 0 ]; then
  REMAIN="$(cat $BAT_PREFIX/$BAT/state | grep remaining | awk '{print $3}')"
  FULL="$(cat $BAT_PREFIX/$BAT/info  | grep last | awk '{print $4}')"
  
  #echo $REMAIN
  #echo $FULL
  RATE="$(echo "scale=2; 100*$REMAIN/$FULL" | bc)"
  echo Laptop: $RATE%
else
  echo Laptop: Not Present.
fi

# 2. Robot Battery
# check for presence of robot
TOPIC=/mobile_base/sensors/core

if ! rostopic info $TOPIC > /dev/null 2>&1; then
  #echo "robot is not loaded yet."
  echo Robot: Not Present.
else
  VAL="$(rostopic echo -n 1 $TOPIC | grep battery | awk '{print $2}')"
  VOLT="$(echo "scale=4; $VAL*0.1" | bc)"
  echo Robot: $VOLT'V'
fi


#ROBOT_FULL=16.4V

#Known Problem:
#   if $TOPIC is advertised but not published, then
#   this script will halted.
