#!/bin/bash
#AUTHOR: Younghun Ju <yhju@yujinrobot.comm>, <yhju83@gmail.com>

# 1. Laptop Battery
REMAIN="$(cat /proc/acpi/battery/BAT0/state | grep remaining | awk '{print $3}')"
FULL="$(cat /proc/acpi/battery/BAT0/info  | grep last | awk '{print $4}')"

#echo $REMAIN
#echo $FULL
RATE="$(echo "scale=2; 100*$REMAIN/$FULL" | bc)"
echo Laptop: $RATE%


# 2. Robot Battery
TOPIC=/mobile_base/sensors/core
VAL="$(rostopic echo -n 1 $TOPIC | grep battery | awk '{print $2}')"
VOLT="$(echo "scale=4; $VAL*0.1" | bc)"

echo Robot: $VOLT'V'
